### ISSUE TITLE
Unable to set up Explore M3 with arduino

### ISSUE THREAD

**Issue by dnvasta** [ExploreEmbedded/Explore-M3#13]
Followed all of your tutorial, regarding driver setup on ubuntu 64-bit, After connecting USB cable, arduino shows a device in COM port, but when i switch to DFU mode by the pressing those keys, green light lits up! Yet the devices doesn't show up in COM port!
I tried checking the device using _lsusb_ command, it showed the device, but in IDE it didn't showed up!
What should i do??

**Comment by dnvasta** [comment]
Can i get a response anytime soon?

**Comment by salmanfarisvp** [comment]
Did you downloaded explore m3 board definition for arduino...?   

- Create a file named install.sh under 

> /.arduino15/packages/ExploreM3/hardware/Explore-M3/1.0.0/tools/linux$
with the following content
```
#!/bin/sh
 
if sudo [ -w /etc/udev/rules.d ]; then
    echo "Copying Explore M3-specific udev rules..."
    sudo cp -v 90-explore-m3.rules /etc/udev/rules.d/90-explore-m3.rules
    sudo chown root:root /etc/udev/rules.d/90-explore-m3.rules
    sudo chmod 644 /etc/udev/rules.d/90-explore-m3.rules
    sudo chmod 777 exploreM3_upload
    sudo chmod 777 upload_reset
    sudo chmod 777 dfu	
    echo "Reloading udev rules"
    sudo udevadm control --reload-rules
    echo "Adding current user to dialout group"
    sudo adduser $USER dialout
else
    echo "Couldn't copy to /etc/udev/rules.d/; you probably have to run this script as root? Or your distribution of Linux doesn't include udev; try running the IDE itself as root."
fi


```

- Run ./install.h (change the file permission if required).



check this please for more info :- https://exploreembedded.com/wiki/Arduino_Setup_for_Explore_M3
